### ISSUE TITLE
No Model Progress

### ISSUE THREAD

**Issue by brianprichardson** [Narsil/alphagozero#4]
Did some more runs with SHOW_END_GAME True.
No model progress at all does not seem right for 63 models.
Before OOM fix (#3), was finding better models (until hitting OOM).

Have a log which I could email you, unless you would rather I post here.
I think my email is public.
Thanks

**Comment by Narsil** [comment]
I'm extremely confused... I left a bug in the v0.5.... 

you can check the latest patch

```
-            value_target = 1 if winner == board[0,0,0,-2] else -1
+            other_player = board[0,0,0,-1] # Current player was changed after having played
+            value_target = -1 if winner == other_player else 1
```

. I'm sorry, I had fixed it, but forgot to add before sending v0.5

**Comment by brianprichardson** [comment]
Ran for 60+ models and the best changed several times.

**Comment by Narsil** [comment]
How is your version doing ? Is it looking like it's making reasonable plays ? 

So far I haven't been able to see good levels of play. I have MCTS batching prediction in prevision.

**Comment by brianprichardson** [comment]
I stopped it after 60+ models.  There were several new "bests" but it did not seem to make any progress after model 14, IIRC.  Perhaps this is to be expected and it should run longer?  I am new to Go and have no idea what is reasonable.  BTW, I assume you are aware of GCP's leela-zero efforts:
https://github.com/gcp/leela-zero

**Comment by Narsil** [comment]
I am aware of leela-zero. I feel the approach is really to have a strong open source Go engine. I just want to understand how the alphago zero was implemented for now.

I'm pretty sure there is a problem knowing that the model did not upgrade between model 14 and model 60. 
- It could be a bug.
- It could be not enough self play: it is playing  250 games instead of 25k. And looking at outputs it seems the models are sometimes very wrong about their assumptions of the board (W and black think W is winning, but in the end black won by a fair margin). It could be that not enough situations have been explored because there are not enough games.
- It could be not enough mcts simulations. Throughout the paper the authors do imply repeatedly that mcts exploration makes the algorithm much stronger.

Right now, I will finish the implementation and test for bugs (GPU distribution and resignation are still missing, but they shouldn't be too hard to implement).

**Comment by brianprichardson** [comment]
Starting a run with v0.6
BTW Please add announcing the version so I know which one I am running.

**Comment by Narsil** [comment]
You can cancel it. I found a few bugs. Some are fixed, some I'm still trying to identify, but just running won't yield good results. 

First model is random, second model beats model 1 by a very large margin (up to 90% winrate). Somehow all subsequent models can't ever beat model2 for some reason. I suspect very simple bugs that I failed to identify. 

Upgrading to batching MCTS the code became more bloat, I'm in the process of reworking it to make it much simpler and more debuggable.
I'm also adding sgf file saves so it's easier to inspect what happen in the different games.

**Comment by brianprichardson** [comment]
OK, stopped until I hear from you again.

**Comment by Narsil** [comment]
It should be fixed on the new version. Had a few bugs as expected. But also the default setting was not simulating deep enough. That means learning is much slower, but the algorithms really needs it in order to improve. 

I've had a few runs with 1600 simulations (Deepmind's defaults) and it was crushing the model that was stuck otherwise. I set the default to 160 simulations which so far seems to be good enough. But we'll have to see. Also, the number of games could be a real game changer (considering deepmind's result, if they require 250k games per new model, I feel the model needs that to progress too)

**Comment by brianprichardson** [comment]
Maybe add sgfmill to requirements.txt ?

BTW I have to sudo python3 main.py to run (create_initial_model ... tf logs permission denied error), but I'm still a Linux newbie so it might just be my setup.  Likewise I have to sudo pip3 install -r requirements.txt

Run started but may take some time.  Currently doing 0.97s/move ... 138s/it of 250 but looks like may be getting faster.

**Comment by Narsil** [comment]
It seems you are having the same kind of setup as me. I left 320 simulations instead of 160.

For you permissions I am not sure all files are created in current directory. 

I did forget sgfmill dependency ! ty.

**Comment by brianprichardson** [comment]
Progress update (looks good to me, but fairly slow):

brian@Tinker2Ubuntu:~/alphagozero/alphagozero$ sudo python3 main.py
Using TensorFlow backend.
Starting run (v0.7)
2017-11-21 21:57:37.568844: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2017-11-21 21:57:37.715851: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-11-21 21:57:37.716321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GTX 1070 major: 6 minor: 1 memoryClockRate(GHz): 1.7845
pciBusID: 0000:03:00.0
totalMemory: 7.92GiB freeMemory: 7.58GiB
2017-11-21 21:57:37.716344: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:03:00.0, compute capability: 6.1)
Self play model_1 163 moves 1.10s/move : 100%|██████████████████████████████████████████████████████| 250/250 [11:03:51<00:00, 159.33s/it]
Loaded latest model model_1.h5
Epochs: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 100/100 [14:22<00:00,  8.63s/it]
Evaluation model_2 vs model_1 (winrate:89% 0.94s/move): 100%|████████████████████████████████████████| 100/100 [4:06:26<00:00, 147.87s/it]
We found a new best model : model_2!
Self play model_2 163 moves 0.96s/move : 100%|██████████████████████████████████████████████████████| 250/250 [10:12:57<00:00, 147.11s/it]
2017-11-22 23:35:47.317913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:03:00.0, compute capability: 6.1)
Loaded latest model model_2.h5
Epochs: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 100/100 [14:07<00:00,  8.47s/it]
Evaluation model_3 vs model_2 (winrate:59% 0.95s/move): 100%|████████████████████████████████████████| 100/100 [4:00:32<00:00, 144.32s/it]
2017-11-23 03:51:11.891375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:03:00.0, compute capability: 6.1)
Loaded latest model model_3.h5
Epochs: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 100/100 [14:02<00:00,  8.43s/it]
Evaluation model_4 vs model_2 (winrate:64% 0.95s/move): 100%|████████████████████████████████████████| 100/100 [3:51:16<00:00, 138.76s/it]
We found a new best model : model_4!
Self play model_4 163 moves 0.96s/move :  21%|███████████▏                                          | 52/250 [1:56:26<7:23:23, 134.36s/it]

**Comment by Narsil** [comment]
As I mentionned it's slower because it has to go deeper in simulations. It still shouldn't be really good at Go though. I'm working on how to make it better/faster.
